#!/usr/bin/env python

# Import from openpyxl
from openpyxl import load_workbook

# Load up the workbook.
wb = load_workbook( "Test.xlsx", read_only=True )

# Repeat the test...
for n in range( 20 ):
    # For each row in the test sheet...
    for row in wb[ "Test Sheet" ].rows:
        # For each cell in the current row...
        for cell in row:
            # Do nothing useful with the value in there.
            value = cell.value

### read-using-generators ends here
